Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "10.10.10.10"


  # transfer code
  config.vm.provision "file", source: ".", destination: "$HOME/kt4", :run => 'always'
  
  # run scripts
  config.vm.provision "shell", path: "vagrantUpdateAndDocker.sh"
  config.vm.provision "shell", path: "vagrantInit.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

end